version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-uxtracking
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    mem_limit: 1024M
    cpus: 1.0
    restart: always

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-uxtracking
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - "8081:8081"
    mem_limit: 256M
    cpus: 0.25
    restart: always

  web:
    build: .
    container_name: web-app-uxtracking
    expose:
      - "8000"
    depends_on:
      - mongo
    env_file:
      - .env
    mem_limit: 2048M
    cpus: 1.0
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-uxtracking
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    mem_limit: 512M
    cpus: 0.5
    restart: always
